"use client";

import type { Block } from "@/types";
import HeroBlockEditor from "./HeroBlockEditor";
import PortfolioGridBlockEditor from "./PortfolioGridBlockEditor";
import ServicesListBlockEditor from "./ServicesListBlockEditor";
import PackPremiumBlockEditor from "./PackPremiumBlockEditor";
import TestimonialsBlockEditor from "./TestimonialsBlockEditor";
import TimelineProcessBlockEditor from "./TimelineProcessBlockEditor";
import FaqAccordionBlockEditor from "./FaqAccordionBlockEditor";
import VideoBlockEditor from "./VideoBlockEditor";
import FullImageBlockEditor from "./FullImageBlockEditor";
import WhyMeBlockEditor from "./WhyMeBlockEditor";
import CenteredCtaBlockEditor from "./CenteredCtaBlockEditor";
import CustomFormBlockEditor from "./CustomFormBlockEditor";
import CalendarBookingBlockEditor from "./CalendarBookingBlockEditor";
import StatsCounterBlockEditor from "./StatsCounterBlockEditor";
import NewsletterBlockEditor from "./NewsletterBlockEditor";
import PricingTableBlockEditor from "./PricingTableBlockEditor";
import FeatureGridBlockEditor from "./FeatureGridBlockEditor";
import TestimonialsCarouselBlockEditor from "./TestimonialsCarouselBlockEditor";
import FaqAdvancedBlockEditor from "./FaqAdvancedBlockEditor";
import TimelineAdvancedBlockEditor from "./TimelineAdvancedBlockEditor";
import CtaPremiumBlockEditor from "./CtaPremiumBlockEditor";
import LogoCloudBlockEditor from "./LogoCloudBlockEditor";
import StatsAnimatedBlockEditor from "./StatsAnimatedBlockEditor";
import MasonryGalleryBlockEditor from "./MasonryGalleryBlockEditor";
import ComparisonTableBlockEditor from "./ComparisonTableBlockEditor";
import ContactFormBlockEditor from "./ContactFormBlockEditor";
import BlogPreviewBlockEditor from "./BlogPreviewBlockEditor";
import VideoTextSplitBlockEditor from "./VideoTextSplitBlockEditor";
import BeforeAfterBlockEditor from "./BeforeAfterBlockEditor";
import ServiceCardsBlockEditor from "./ServiceCardsBlockEditor";
import LeadMagnetBlockEditor from "./LeadMagnetBlockEditor";
import AvailabilityBannerBlockEditor from "./AvailabilityBannerBlockEditor";
import ProductHeroCheckoutBlockEditor from "./ProductHeroCheckoutBlockEditor";
import ProductCardsGridBlockEditor from "./ProductCardsGridBlockEditor";
import InlineCheckoutBlockEditor from "./InlineCheckoutBlockEditor";
import BundleBuilderBlockEditor from "./BundleBuilderBlockEditor";
import PricingTableRealBlockEditor from "./PricingTableRealBlockEditor";
import HeroSplitGlowBlockEditor from "./HeroSplitGlowBlockEditor";
import HeroCenteredMeshBlockEditor from "./HeroCenteredMeshBlockEditor";
import ServicesPremiumBlockEditor from "./ServicesPremiumBlockEditor";
import PortfolioMasonryBlockEditor from "./PortfolioMasonryBlockEditor";
import PricingModernBlockEditor from "./PricingModernBlockEditor";
import TestimonialsDarkBlockEditor from "./TestimonialsDarkBlockEditor";
import CtaBannerBlockEditor from "./CtaBannerBlockEditor";
import ContactPremiumBlockEditor from "./ContactPremiumBlockEditor";
import FooterBlockEditor from "./FooterBlockEditor";
import VideoShowcaseBlockEditor from "./VideoShowcaseBlockEditor";
import TechStackBlockEditor from "./TechStackBlockEditor";
import BeforeAfterProBlockEditor from "./BeforeAfterProBlockEditor";
// ─── 50 new block editors ───
import HeroSplitPortfolioBlockEditor from "./HeroSplitPortfolioBlockEditor";
import HeroMinimalServiceBlockEditor from "./HeroMinimalServiceBlockEditor";
import HeroDarkSaasBlockEditor from "./HeroDarkSaasBlockEditor";
import HeroCreatorBrandBlockEditor from "./HeroCreatorBrandBlockEditor";
import HeroVideoShowreelBlockEditor from "./HeroVideoShowreelBlockEditor";
import ProjectsGridCasesBlockEditor from "./ProjectsGridCasesBlockEditor";
import ProjectsHorizontalBlockEditor from "./ProjectsHorizontalBlockEditor";
import ProjectBeforeAfterBlockEditor from "./ProjectBeforeAfterBlockEditor";
import ProjectTimelineBlockEditor from "./ProjectTimelineBlockEditor";
import ProjectMasonryWallBlockEditor from "./ProjectMasonryWallBlockEditor";
import Services3CardPremiumBlockEditor from "./Services3CardPremiumBlockEditor";
import ServicesIconGridBlockEditor from "./ServicesIconGridBlockEditor";
import ServicesSplitValueBlockEditor from "./ServicesSplitValueBlockEditor";
import ServicesProcessOffersBlockEditor from "./ServicesProcessOffersBlockEditor";
import ProductFeaturedCardBlockEditor from "./ProductFeaturedCardBlockEditor";
import Products3CardShopBlockEditor from "./Products3CardShopBlockEditor";
import ProductBundleCompareBlockEditor from "./ProductBundleCompareBlockEditor";
import ProductBenefitsMockupBlockEditor from "./ProductBenefitsMockupBlockEditor";
import Pricing3TierSaasBlockEditor from "./Pricing3TierSaasBlockEditor";
import PricingCustomQuoteBlockEditor from "./PricingCustomQuoteBlockEditor";
import PricingMiniFaqBlockEditor from "./PricingMiniFaqBlockEditor";
import Testimonials3DarkBlockEditor from "./Testimonials3DarkBlockEditor";
import TestimonialsVideoBlockEditor from "./TestimonialsVideoBlockEditor";
import ResultsLogosQuotesBlockEditor from "./ResultsLogosQuotesBlockEditor";
import NumbersImpactBlockEditor from "./NumbersImpactBlockEditor";
import ResultsTimelineBlockEditor from "./ResultsTimelineBlockEditor";
import AboutPersonalStoryBlockEditor from "./AboutPersonalStoryBlockEditor";
import AboutStudioValuesBlockEditor from "./AboutStudioValuesBlockEditor";
import TeamMiniGridBlockEditor from "./TeamMiniGridBlockEditor";
import Process4StepsBlockEditor from "./Process4StepsBlockEditor";
import ProcessDetailedTimelineBlockEditor from "./ProcessDetailedTimelineBlockEditor";
import FaqAccordionFullBlockEditor from "./FaqAccordionFullBlockEditor";
import Faq2ColumnBlockEditor from "./Faq2ColumnBlockEditor";
import CtaCenteredStrongBlockEditor from "./CtaCenteredStrongBlockEditor";
import CtaSplitTextBlockEditor from "./CtaSplitTextBlockEditor";
import CtaDarkGlowBlockEditor from "./CtaDarkGlowBlockEditor";
import FormContactSimpleBlockEditor from "./FormContactSimpleBlockEditor";
import FormQuoteRequestBlockEditor from "./FormQuoteRequestBlockEditor";
import FormNewsletterLeadBlockEditor from "./FormNewsletterLeadBlockEditor";
import MediaFeaturedVideoBlockEditor from "./MediaFeaturedVideoBlockEditor";
import Gallery3UpStripBlockEditor from "./Gallery3UpStripBlockEditor";
import GalleryStackedStoryboardBlockEditor from "./GalleryStackedStoryboardBlockEditor";
import ContentFeatureArticleBlockEditor from "./ContentFeatureArticleBlockEditor";
import Content3ArticlesBlockEditor from "./Content3ArticlesBlockEditor";
import ContentComparisonWhyBlockEditor from "./ContentComparisonWhyBlockEditor";
import TrustBadgesBlockEditor from "./TrustBadgesBlockEditor";
import SocialProofMarqueeBlockEditor from "./SocialProofMarqueeBlockEditor";
import FooterSimplePremiumBlockEditor from "./FooterSimplePremiumBlockEditor";
import FooterMultiColumnBlockEditor from "./FooterMultiColumnBlockEditor";
import SignatureCreativeClosingBlockEditor from "./SignatureCreativeClosingBlockEditor";
import { useBuilder } from "@/lib/site-builder-context";

export default function BlockEditor({ block }: { block: Block }) {
  const { dispatch } = useBuilder();
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const contentChange = (c: any) => dispatch({ type: "UPDATE_BLOCK_CONTENT", blockId: block.id, content: c });

  switch (block.type) {
    case "hero": return <HeroBlockEditor block={block} />;
    case "portfolio-grid": return <PortfolioGridBlockEditor block={block} />;
    case "services-list": return <ServicesListBlockEditor block={block} />;
    case "pack-premium": return <PackPremiumBlockEditor block={block} />;
    case "testimonials": return <TestimonialsBlockEditor block={block} />;
    case "timeline-process": return <TimelineProcessBlockEditor block={block} />;
    case "faq-accordion": return <FaqAccordionBlockEditor block={block} />;
    case "video": return <VideoBlockEditor block={block} />;
    case "full-image": return <FullImageBlockEditor block={block} />;
    case "why-me": return <WhyMeBlockEditor block={block} />;
    case "centered-cta": return <CenteredCtaBlockEditor block={block} />;
    case "custom-form": return <CustomFormBlockEditor block={block} />;
    case "calendar-booking": return <CalendarBookingBlockEditor block={block} />;
    case "stats-counter": return <StatsCounterBlockEditor block={block} />;
    case "newsletter": return <NewsletterBlockEditor block={block} />;
    case "pricing-table": return <PricingTableBlockEditor block={block} />;
    case "feature-grid": return <FeatureGridBlockEditor block={block} />;
    case "testimonials-carousel": return <TestimonialsCarouselBlockEditor block={block} />;
    case "faq-advanced": return <FaqAdvancedBlockEditor block={block} />;
    case "timeline-advanced": return <TimelineAdvancedBlockEditor block={block} />;
    case "cta-premium": return <CtaPremiumBlockEditor block={block} />;
    case "logo-cloud": return <LogoCloudBlockEditor block={block} />;
    case "stats-animated": return <StatsAnimatedBlockEditor block={block} />;
    case "masonry-gallery": return <MasonryGalleryBlockEditor block={block} />;
    case "comparison-table": return <ComparisonTableBlockEditor block={block} />;
    case "contact-form": return <ContactFormBlockEditor block={block} />;
    case "blog-preview": return <BlogPreviewBlockEditor block={block} />;
    case "video-text-split": return <VideoTextSplitBlockEditor block={block} />;
    case "before-after": return <BeforeAfterBlockEditor block={block} />;
    case "service-cards": return <ServiceCardsBlockEditor block={block} />;
    case "lead-magnet": return <LeadMagnetBlockEditor block={block} />;
    case "availability-banner": return <AvailabilityBannerBlockEditor block={block} />;
    case "product-hero-checkout": return <ProductHeroCheckoutBlockEditor content={block.content} onChange={contentChange} />;
    case "product-cards-grid": return <ProductCardsGridBlockEditor content={block.content} onChange={contentChange} />;
    case "inline-checkout": return <InlineCheckoutBlockEditor content={block.content} onChange={contentChange} />;
    case "bundle-builder": return <BundleBuilderBlockEditor content={block.content} onChange={contentChange} />;
    case "pricing-table-real": return <PricingTableRealBlockEditor content={block.content} onChange={contentChange} />;
    case "hero-split-glow": return <HeroSplitGlowBlockEditor block={block} />;
    case "hero-centered-mesh": return <HeroCenteredMeshBlockEditor block={block} />;
    case "services-premium": return <ServicesPremiumBlockEditor block={block} />;
    case "portfolio-masonry": return <PortfolioMasonryBlockEditor block={block} />;
    case "pricing-modern": return <PricingModernBlockEditor block={block} />;
    case "testimonials-dark": return <TestimonialsDarkBlockEditor block={block} />;
    case "cta-banner": return <CtaBannerBlockEditor block={block} />;
    case "contact-premium": return <ContactPremiumBlockEditor block={block} />;
    case "footer-block": return <FooterBlockEditor block={block} />;
    case "video-showcase": return <VideoShowcaseBlockEditor block={block} />;
    case "tech-stack": return <TechStackBlockEditor block={block} />;
    case "before-after-pro": return <BeforeAfterProBlockEditor block={block} />;
    // ─── 50 new blocks ───
    case "hero-split-portfolio": return <HeroSplitPortfolioBlockEditor block={block} />;
    case "hero-minimal-service": return <HeroMinimalServiceBlockEditor block={block} />;
    case "hero-dark-saas": return <HeroDarkSaasBlockEditor block={block} />;
    case "hero-creator-brand": return <HeroCreatorBrandBlockEditor block={block} />;
    case "hero-video-showreel": return <HeroVideoShowreelBlockEditor block={block} />;
    case "projects-grid-cases": return <ProjectsGridCasesBlockEditor block={block} />;
    case "projects-horizontal": return <ProjectsHorizontalBlockEditor block={block} />;
    case "project-before-after": return <ProjectBeforeAfterBlockEditor block={block} />;
    case "project-timeline": return <ProjectTimelineBlockEditor block={block} />;
    case "project-masonry-wall": return <ProjectMasonryWallBlockEditor block={block} />;
    case "services-3card-premium": return <Services3CardPremiumBlockEditor block={block} />;
    case "services-icon-grid": return <ServicesIconGridBlockEditor block={block} />;
    case "services-split-value": return <ServicesSplitValueBlockEditor block={block} />;
    case "services-process-offers": return <ServicesProcessOffersBlockEditor block={block} />;
    case "product-featured-card": return <ProductFeaturedCardBlockEditor block={block} />;
    case "products-3card-shop": return <Products3CardShopBlockEditor block={block} />;
    case "product-bundle-compare": return <ProductBundleCompareBlockEditor block={block} />;
    case "product-benefits-mockup": return <ProductBenefitsMockupBlockEditor block={block} />;
    case "pricing-3tier-saas": return <Pricing3TierSaasBlockEditor block={block} />;
    case "pricing-custom-quote": return <PricingCustomQuoteBlockEditor block={block} />;
    case "pricing-mini-faq": return <PricingMiniFaqBlockEditor block={block} />;
    case "testimonials-3dark": return <Testimonials3DarkBlockEditor block={block} />;
    case "testimonials-video": return <TestimonialsVideoBlockEditor block={block} />;
    case "results-logos-quotes": return <ResultsLogosQuotesBlockEditor block={block} />;
    case "numbers-impact": return <NumbersImpactBlockEditor block={block} />;
    case "results-timeline": return <ResultsTimelineBlockEditor block={block} />;
    case "about-personal-story": return <AboutPersonalStoryBlockEditor block={block} />;
    case "about-studio-values": return <AboutStudioValuesBlockEditor block={block} />;
    case "team-mini-grid": return <TeamMiniGridBlockEditor block={block} />;
    case "process-4steps": return <Process4StepsBlockEditor block={block} />;
    case "process-detailed-timeline": return <ProcessDetailedTimelineBlockEditor block={block} />;
    case "faq-accordion-full": return <FaqAccordionFullBlockEditor block={block} />;
    case "faq-2column": return <Faq2ColumnBlockEditor block={block} />;
    case "cta-centered-strong": return <CtaCenteredStrongBlockEditor block={block} />;
    case "cta-split-text": return <CtaSplitTextBlockEditor block={block} />;
    case "cta-dark-glow": return <CtaDarkGlowBlockEditor block={block} />;
    case "form-contact-simple": return <FormContactSimpleBlockEditor block={block} />;
    case "form-quote-request": return <FormQuoteRequestBlockEditor block={block} />;
    case "form-newsletter-lead": return <FormNewsletterLeadBlockEditor block={block} />;
    case "media-featured-video": return <MediaFeaturedVideoBlockEditor block={block} />;
    case "gallery-3up-strip": return <Gallery3UpStripBlockEditor block={block} />;
    case "gallery-stacked-storyboard": return <GalleryStackedStoryboardBlockEditor block={block} />;
    case "content-feature-article": return <ContentFeatureArticleBlockEditor block={block} />;
    case "content-3articles": return <Content3ArticlesBlockEditor block={block} />;
    case "content-comparison-why": return <ContentComparisonWhyBlockEditor block={block} />;
    case "trust-badges": return <TrustBadgesBlockEditor block={block} />;
    case "social-proof-marquee": return <SocialProofMarqueeBlockEditor block={block} />;
    case "footer-simple-premium": return <FooterSimplePremiumBlockEditor block={block} />;
    case "footer-multi-column": return <FooterMultiColumnBlockEditor block={block} />;
    case "signature-creative-closing": return <SignatureCreativeClosingBlockEditor block={block} />;
  }
}
